import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime


def send_alert(url, findings, sender, password, recipient):
    """
    Automatically send email if Critical or High issues found.
    Returns True if email sent, False if not.
    """

    # Filter only Critical and High findings
    serious = []
    for finding in findings:
        if finding["severity"] in ["Critical", "High"]:
            serious.append(finding)

    # If no serious issues, don't send email
    if not serious:
        print("No Critical/High issues — email not sent")
        return False

    # Build email subject
    subject = f"SECURITY ALERT — {len(serious)} Critical/High issues found on {url}"

    # Build plain text body
    body = f"""
VULNSCAN SECURITY ALERT
========================
Target URL  : {url}
Scan Time   : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Issues Found: {len(serious)} Critical/High vulnerabilities

CRITICAL & HIGH FINDINGS:
"""

    for finding in serious:
        body += f"""
Vulnerability : {finding['name']}
Severity      : {finding['severity']}
Score         : {finding['score']}/10
Description   : {finding['description']}
Fix           : {finding['fix']}
---
"""

    body += """
DISCLAIMER:
This alert was automatically generated by VulnScan.
Only scan websites you have permission to test.
Unauthorized scanning may be illegal.
"""

    # Create email message
    msg = MIMEMultipart()
    msg["From"]    = sender
    msg["To"]      = recipient
    msg["Subject"] = subject
    msg.attach(MIMEText(body, "plain"))

    # Send email using Gmail SMTP
    try:
        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login(sender, password)
        server.send_message(msg)
        server.quit()
        print(f"Alert email sent to {recipient}!")
        return True
    except Exception as e:
        print(f"Email failed: {e}")
        return False
